ProjectCode/Project/Project/Controllers/BarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Project.Models;
using PagedList;
using Microsoft.AspNet.Identity;

namespace Project.Controllers
{
    public class BarsController : Controller
    {
        /**
         * Retun the overview of the bars 
         * page = the current page
         **/
        public ActionResult Index(int? page)
        {
            barFilterModel m = new barFilterModel();
            m.Page = page;
            m.PagedBars = bar.GetAllBars().ToPagedList(m.Page ?? 1, 6);
            return View(m);
        }

        /**
         * Detail view of a bar 
         * rev =  the review of the currently logged in user
         * id = the id of the requested bar
         **/
        public ActionResult Detail(review_bar rev, int id)
        {
            ViewBag.bar = bar.GetBarByID(id);
            ViewBag.reviews = bar.GetReviewsFromBarID(id).OrderByDescending(x => x.id); ;
            if (user.getUser() != null)
            {
                rev = null;
                rev = review_bar.GetReviewForEventByUser(id, user.getUser().id);
                if (rev != null)
                {
                    TempData["Review_ID"] = rev.id;
                }
            }

            ViewBag.events = @event.GetAllEvents().Where(x => x.BarID == id).OrderBy(x => x.DT).Take(3);

            TempData["Detail_ID"] = id;

            return View(rev);
        }

        /**
         * Filter for the bars 
         **/
        public ActionResult Filter(barFilterModel m)
        {
            if (m.Page == null)
            {
                TempData["Name"] = m.Name;
                TempData["City"] = m.City;
            }
            else
            {
                m.Name = (string)TempData["Name"];
                m.City = (string)TempData["City"];
            }

            TempData.Keep();

            m.PagedBars = bar.GetFilteredBars(m).ToPagedList(m.Page ?? 1, 6);

            return View("Index", m);
        }

        /**
         * Adds a review to the bar
         * rev = contains the rating and the description
         **/
        [HttpPost]
        public ActionResult Detail(review_bar rev)
        {
            int id = (int)TempData["Detail_ID"];
            rev.id = 0;
            if (TempData["Review_ID"] != null)
            {
                rev.id = (int)TempData["Review_ID"];
            }

            if (ModelState.IsValid)
            {
                if (rev.id == 0)
                {
                    rev.id = review_bar.getNewIdReview();
                }
                rev.user_id = user.getUser().id;
                rev.bars_id = id;

                if (!review_bar.Add_Review(rev))
                {
                    ModelState.AddModelError("Review", "Je kan maximaal 1 review toevoegen aan een bar");
                }
                else
                {
                    return RedirectToAction("Detail", new { id = id });
                }
            }

            ViewBag.bar = bar.GetBarByID(id);
            ViewBag.reviews = bar.GetReviewsFromBarID(id).OrderByDescending(x => x.id);
            ViewBag.events = @event.GetAllEvents().Where(x => x.BarID == id).OrderBy(x => x.DT).Take(3);

            TempData.Keep();
            return View(rev);
        }

       
    }
}

ProjectCode/Project/Project/Controllers/EventsController.cs
using PagedList;
using Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Controllers
{
    public class EventsController : Controller
    {
        // GET: Events
        public ActionResult Index(int? page)
        {
            eventFilterModel model = new eventFilterModel();

            model.Page = page;
            model.PagedEvents = @event.GetAllEvents().OrderBy(x=> x.DT).ToPagedList(model.Page ?? 1, 6);
            model.Genres = @event.getAllGenres();

            return View(model);
        }

        /**
         * Return the Detail view
         * id = the id of the event
         **/
        public ActionResult Detail(int id)
        {

            var test = @event.GetEventByID(id);
            ViewBag.ev = test;
            ViewBag.events = @event.GetAllEvents().Where(x => x.BarID == test.BarID && x.ID != test.ID).OrderBy(x => x.DT).Take(3);
            TempData["Detail_ID"] = id;
            ViewBag.Reviews = comment_event.GetCommentsFromEventID(id).OrderByDescending(x => x.id);
            return View();
        }

        /**
         * return the filtered events
         * m = an object of the filters
         **/
        public ActionResult Filter(eventFilterModel m)
        {
            if (m.Page == null)
            {
                TempData["Name"] = m.Name;
                TempData["Genre"] = m.Genre_ID;
                TempData["City"] = m.City;
                TempData["Barname"] = m.BarName;
            }
            else
            {
                m.Name = (string)TempData["Name"];
                m.Genre_ID = (string)TempData["Genre"];
                m.City = (string)TempData["City"];
                m.BarName = (string)TempData["Barname"];
            }

            TempData.Keep();

            m.PagedEvents = @event.GetFilteredEvents(m).OrderBy(x=> x.DT).ToPagedList(m.Page ?? 1, 6);

            m.Genres = @event.getAllGenres();

            return View("Index", m);
        }

        /**
         * Return the Detail view after adding a new comment to an event
         * com = the new comment
         **/
        [HttpPost]
        public ActionResult Detail(comment_event com)
        {
            int id = (int)TempData["Detail_ID"];

            if (ModelState.IsValid)
            {
                com.events_id = id;
                com.user_id = user.getUser().id;

                if (!comment_event.Add_Comment(com))
                {
                    ModelState.AddModelError("Review", "Er ging iets mis, probeer opnieuw.");
                }
                else
                {
                    return RedirectToAction("Detail", new { id = id });
                }
            }
            
            ViewBag.reviews = bar.GetReviewsFromBarID(id);
            
            ViewBag.ev = @event.GetEventByID(id);

            TempData.Keep();
            return View(com);
        }
    }
}

ProjectCode/Project/Project/Controllers/HomeController.cs
using Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Controllers
{
    public class HomeController : Controller
    {
        /**
         * Home index 
         **/
        public ActionResult Index()
        {
            ViewBag.bars = bar.GetAllBars().OrderBy(a => Guid.NewGuid()).Take(3).ToList();
            ViewBag.events = @event.GetAllEvents().OrderBy(a => Guid.NewGuid()).Take(3);
            return View();
        }
    }
}

ProjectCode/Project/Project/Views/Home/Index.cshtml
@{
    ViewBag.Title = "PopItUp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using Project.Models;

<div id="features">
    <!-- Page Content -->
    <div class="container">

        <div class="row" id="all_features">
            <div class="col-xs-12 text-center">
                <h2>POPITUP</h2>
            </div>
            <p id="features_text_top">
                Pop-up bars zijn populairder dan ooit!
            </p>
            <p id="features_text_top">
                Dankzij <strong>PopItUp</strong> kan je makkelijk:
            </p>
            <div class="features">
                <div class="col-xs-4 categories">
                    <img src="@Url.Content("~/Content/Images/bar.png")">
                    <p id="features_text">
                        Nabije bars ontdekken!
                    </p>
                </div>

                <div class="col-xs-4 categories">
                    <img src="@Url.Content("~/Content/Images/event.png")">
                    <p id="features_text">
                        Toffe evenementen vinden!
                    </p>
                </div>

                <div class="col-xs-4 categories">
                    <img src="@Url.Content("~/Content/Images/rating.png")">
                    <p id="features_text">
                        Reviews lezen en achterlaten!
                    </p>
                </div>
            </div>
            @if (!User.Identity.IsAuthenticated)
            {
                <div class="col-xs-12 text-center" id="showAll">
                    @Html.ActionLink("Registreer nu!", "Register", "Account", routeValues: new { }, htmlAttributes: new { @class = "btn btn-info btn-lg register" })
                </div>
            } else
            {
                <div class="row" id="whitespace">
                    <p> </p>
                </div>
            }
        </div>

    </div>
</div>

<div class="container">
    <div class="col-xs-12">
        <h2 class="text-center previews">Enkele bars</h2>
        @foreach (bar_object bar in ViewBag.bars)
        {
            <div class="col-xs-4 preview_item">
                <a class="picture-link" href="@Url.Action("Detail", "Bars", routeValues: new { id = bar.ID })"><img src="@Url.Content("~/Content/Images/" +@bar.Name.Replace(' ', '_') + ".jpg")"></a>

                <h3 class="activities_header">
                    @bar.Name
                </h3>
                @Html.ActionLink("Meer over " + @bar.Name, "Detail", "Bars", routeValues: new { id = bar.ID }, htmlAttributes: new { @class = "btn btn-info" })
            </div>
        }
    </div>
    
    <div class="text-center" id="showAll">
        @Html.ActionLink("Toon alle bars", "Index", "Bars", routeValues: new { }, htmlAttributes: new { @class = "btn btn-info btn-lg" })
    </div>
  
</div>

<div class="container">
    <div class="col-xs-12">
        <h2 class="text-center previews">Enkele Evemenenten</h2>
        @foreach (event_object ev in ViewBag.events)
        {
            <div class="col-xs-4 preview_item">
                <a class="picture-link" href="@Url.Action("Detail", "Events", routeValues: new { id = ev.ID })"><img onerror='this.onerror=null; this.src="@Url.Content("~/Content/Images/dummyEvent.png")"' src="@Url.Content("~/Content/Images/Events/" + @ev.ID + ".jpg")"></a>

                <h3 class="activities_header">
                    @ev.Name
                </h3>

                @Html.ActionLink("Meer over " + ev.Name, "Detail", "Events", routeValues: new { id = ev.ID }, htmlAttributes: new { @class = "btn btn-info" })
            </div>
        }
        <div class="text-center" id="showAll">
            @Html.ActionLink("Toon alle evenementen", "Index", "Events", routeValues: new { }, htmlAttributes: new { @class = "btn btn-info btn-lg" })
        </div>
    </div>
    
</div>